services:
  redis:
    image: redis:5.0.7-alpine

  app:
    build: .
    command: ["python", "main.py"]
    volumes:
      - ./:/app
    depends_on:
      - redis

  celery:
    build: .
    command: ["celery", "-A", "proj", "worker"]
    volumes:
      - ./:/app
    depends_on:
      - redis
